import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

// Define Strapi URL
const STRAPI_URL = "http://localhost:1337";

export default function Home(props) {
  const [articles, setArticles] = useState([]);

  useEffect(() => {
    getArticles();
  }, []);


  const getArticles = async () => {
    const response = await fetch(`${STRAPI_URL}/api/articles?populate=*`);
    const data = await response.json();
    console.log(data.data)
    setArticles(data.data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <Image
            src="/assets/images/logo/duce-logo.svg"
            alt="Next.js logo"
            width={180}
            height={100}
            priority
          />
          <div>
            <h1>Blog posts from Strapi</h1>
            <div>
              <h2>Articles</h2>
              <div>
                {articles.map((article) => (
                  <article
                    key={article.id}
                  >
                    {Array.isArray(article.cover) ? (
                      article.cover.map((cover, index) => (
                        <Image
                          key={index}
                          src={STRAPI_URL + article.cover[index].url}
                          alt={`Article ${index + 1} Cover`}
                          width={180}
                          height={38}
                          priority
                        />
                      ))
                    ) : (
                      <div>
                        <p>No cover image available</p>
                      </div>
                    )}
                    <div>
                      <h3>
                        {article.title}
                      </h3>
                      <p>{article.content}</p>
                      <p>
                        Published: {article.publishedAt}
                      </p>
                    </div>
                  </article>
                ))}
              </div>
            </div>
          </div>
        </main>
        <footer>
          ©2025 Duce. All rights reserved.
        </footer>
      </div>
    </>
  );
}
